# .github/workflows/compile.yml (Final Version using Pterodactyl Image)
name: Compile Node.js Dependencies

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # We still use a standard runner to orchestrate the job
    runs-on: ubuntu-latest

    # --- THE CRITICAL CHANGE IS HERE ---
    # This tells GitHub Actions to run all subsequent steps inside this specific Docker container.
    container:
      image: quay.io/yajtpg/pterodactyl-images:nodejs-20

    steps:
    # Step 1: Check out the repository code
    # The code will be automatically mounted into the container's workspace.
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install dependencies
    # This command now runs INSIDE the Pterodactyl Node.js 20 container,
    # guaranteeing a perfect compilation match.
    - name: Install dependencies
      run: npm install

    # Step 3: Compress the resulting node_modules folder
    # This also runs inside the container.
    - name: Archive node_modules
      run: zip -r node_modules.zip ./node_modules

    # Step 4: Upload the zip file as a downloadable artifact
    # This action runs on the host runner but knows how to access files from the container's workspace.
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-node-modules
        path: node_modules.zip
