# .github/workflows/compile.yml (Final Version for Maximum Compatibility)
name: Compile Node.js Dependencies

on:
  workflow_dispatch:
  schedule:
    # This runs at 00:00 UTC every day.
    - cron: '0 0 * * *'

jobs:
  build:
    # Use a standard, modern build environment provided by GitHub.
    # This ensures we have an up-to-date C++ compiler.
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up the correct Node.js version.
    # This ensures the native addon is compiled for Node.js v20.11.0.
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'

    # Step 3: Install all dependencies.
    # This will run on the modern Ubuntu VM and succeed.
    - name: Install dependencies
      run: npm install

    # Step 4: Compress the resulting node_modules folder
    - name: Archive node_modules
      run: zip -r node_modules.zip ./node_modules

    # Step 5: Upload the zip file as a downloadable artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-node-modules
        path: node_modules.zip
